### ISSUE TITLE
Model Release?

### ISSUE THREAD

**Issue by nunbuzor** [feizc/Dimba#1]
Thank you for sharing your work on Dimba.

I noticed that the model files are not available in this repository. Could you please upload them? Having access to these files would be incredibly helpful for those of us looking to see Dimba in action.

Thanks!

**Comment by Njasa2k** [comment]
+1

**Comment by TruthSearcher** [comment]
+1

**Comment by feizc** [comment]
Hi, the ckpts and datasets will be submitted to HF as soon as possible. Please wait a moment :)
